### PR TITLE
User Input Validation

### LINKED ISSUE #8: Users should not be able to enter obviously incorrect expressions
## Current State

A user may enter any combination of symbols on the calculator.

## Problem

Because a user may enter any combination of symbols, they may enter syntactically incorrect expressions. Although the interpreter can handle these expressions and report an error, this results in a poor user experience. An invalid expression should be prevented if it can.

## Solution

1. The UI should only allow starting an expression with a numeric value, p-symbol, unary minus, or an open parenthesis. After the initial entry, the user would enter a numeric value or a symbol depending on the previous entry. This would prevent a large portion of invalid expressions.

## Questions

1. Should the user be alerted when they click a button that would lead to an invalid expression, or is it enough not to update the display?

### PR DESCRIPTION
**Pull request by andrewleverette**
Add logic to prevent a user from entering incorrect expressions. This prevents the bulk of all possible incorrect expressions, but not all of them.

### CODE REVIEW

File: src/clojulator/web/core.cljs [hunk 1]
```diff
@@ -1,38 +1,106 @@
...
+                                               :alert/visble false
+                                               :alert/timeout-id nil}}))
 
 ;; Event Handlers
+(defn- trigger-alert!
+  [timeout-id timeout-value event]
+  (when timeout-id
+    (js/clearTimeout timeout-id))
+  (let [new-timeout-id (js/setTimeout (fn [] (apply swap! state! assoc-in event)) timeout-value)]
+    [[:state/alert :alert/timeout-id] new-timeout-id]))
```
Comment (PEZ) [inline src/clojulator/web/core.cljs]: Here you swap on the state “out of band”. It's probably fine (I honestly don't know), but you can arrange things so that you only mutate the state at one place. The way I know to do it is to dispatch a Replicant event on the timer, instead of mutating.
